source_repo: "mongodb/docs-code-examples"
source_branch: "main"

copy_rules:
  - name: "all-generated-examples"
    source_pattern:
      type: "glob"
      pattern: "generated-usage-examples/**/*"
    targets:
      - repo: "mongodb/atlas-architecture-cli"
        branch: "main"
        path_transform: "${path}"
        commit_strategy:
          type: "pull_request"
          pr_title: "Update code examples from docs-code-examples PR #${pr_number}"
          pr_body: |
            Automated update of code examples from docs-code-examples.
            
            Source PR: #${pr_number}
            Commit: ${commit_sha}
            
            Files updated:
            - See commits for details
          commit_message: "Update code examples from PR #${pr_number}"
