source_repo: mongodb/docs-code-examples
source_branch: test

copy_configs:
  # Configuration for Go examples with pattern matching and transforms
  generated-usage-examples/go:
    pattern_config:
      type: glob
      include:
        - "generated-usage-examples/go/**/*"
      transforms:
        - from: "generated-usage-examples/go/atlas-sdk-go/project-copy/${nameWithoutExt}.${ext}"
          to: "code-samples/${dir}/${nameWithoutExt}.${ext}"
    targets:
      - repo: mongodb/atlas-architecture-cli
        branch: v2
        target_path: examples/
    commit_strategy:
      type: pr
      auto_merge: false
      pr_title: "REVIEW REQUIRED: Critical examples updated"

  # Configuration for all generated usage examples (simple copy)
  generated-usage-examples:
    targets:
      - repo: mongodb/atlas-architecture-cli
        branch: v2
        target_path: examples-v2/

default_commit_strategy:
  type: direct
  commit_message: "Automated update from source repo"

default_committer:
  name: "Examples Copier Bot"
  email: "copier@example.com"

recursive_copy: true
dry_run: false
